### ISSUE TITLE
Update for media_player.xbox_one fails

### ISSUE THREAD

**Issue by varyamereon** [tuxuser/hassio-addons#13]
I am getting this error over and over again in the logs:

Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/xboxone/media_player.py:450
First occurred: 3:05:31 PM (4 occurrences)
Last logged: 3:06:04 PM

Update for media_player.xbox_one fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xboxone/media_player.py", line 612, in update
    self._xboxone.refresh()
  File "/config/custom_components/xboxone/media_player.py", line 467, in refresh
    if not self._check_server():
  File "/config/custom_components/xboxone/media_player.py", line 450, in _check_server
    version = resp['versions']['xbox-smartglass-rest']
KeyError: 'xbox-smartglass-rest'

I have had intermittent trouble getting the REST server to connect but I can confim at this time it is connected.

**Comment by tuxuser** [comment]
You are using the old version of the custom component.
Please use HACS to upgrade to the latest: https://github.com/OpenXbox/xboxone-home-assistant/blob/master/info.md

**Comment by varyamereon** [comment]
Thanks @tuxuser for getting back. In HACS it shows I am running the latest version:

Xbox One - smartglass media player
Last updated: 21 days ago
Installed: 446169a
Available: 446169a

Perhaps I'll try a reinstall and see if that helps.

**Comment by varyamereon** [comment]
I can confirm the reinstall worked! No more messages and the component is functioning as expected.

Thanks!!
